### ISSUE TITLE
[BUG] Inconsistencies in CS assertion generation

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1202]
**Describe the bug**
The generation of the XML assertions seems inconsistent. For example the assertion "contain the value 'VALUE'." and "contain the value 'VALUE' (DESCRIPTION)." must generate the same XML. When checking by using the Generate XML assertion button, we can see that it is not the case.

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/601037848b87bc0007089280/datatype/6010378e8b87bc0007089a7b/conformance-statement

**To Reproduce**
1. Create an object flavor (datatype flavor for example)
2. Click on 'Conformance statements" and "New"
3. Choose "Simple"
4. Select a primitive element for Target Node Location
5. Select any verb
6. Select the first assertion type (contain the value 'VALUE'.) and enter a value
7. Click on "Generate XML Assertion" and look at the generated assertion
8. Change the assertion type to "contain the value 'VALUE' (DESCRIPTION)." and enter values
9. Click on "Generate XML Assertion" and look at the generated assertion : the XML assertion should be the same as in step 7 but it is not.

**Expected behavior**
I am expecting the following assertions:
- contain the value 'VALUE'.
- contain the value 'VALUE' (DESCRIPTION).
- contain the value ‘VALUE’ (DESCRIPTION) drawn from the code system 'CODE SYSTEM'.
- contain the value 'VALUE' drawn from the code system 'CODE SYSTEM'.

To generate the same XML.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/105868727-78cf1c80-5fc4-11eb-939e-4e8d1af8fd7b.png)

![image](https://user-images.githubusercontent.com/13591511/105868655-67861000-5fc4-11eb-977b-dd619f0a97f0.png)

![image](https://user-images.githubusercontent.com/13591511/105868809-8c7a8300-5fc4-11eb-9664-2fe0af374ab2.png)

![image](https://user-images.githubusercontent.com/13591511/105868881-a4ea9d80-5fc4-11eb-8d87-f812808f5d9c.png)

**Additional context**
Same checks should be done for the assertions with list of values

**Comment by Jungyubw** [comment]
Fixed

**Comment by Jungyubw** [comment]
Fixed with #1200

**Comment by carolinerosin** [comment]
02 09 2021 QA update
I'm testing on hit dev, I still see that the assertion is not generated for this one 
![image](https://user-images.githubusercontent.com/13591511/107393205-86a69680-6ac8-11eb-81d4-0a3d53138372.png)

Also the generate assertion button does not show anything for this one
![image](https://user-images.githubusercontent.com/13591511/107393482-dc7b3e80-6ac8-11eb-9534-fc32a247eeb2.png)

**Comment by Jungyubw** [comment]
Fixed and requested MR
@carolinerosin Please do QA again after deployment
