### ISSUE TITLE
[BUG] Verification not catching error when a segment flavor is duplicated

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1226]
**Describe the bug**
I managed the create an IG with the same segment flavor duplicated (another issue that we will need to look into, related to custom structures #1225 ). 
When exporting the XML, the verification did not show any error. I was able to export to XML. If I validate against the schemas, I get an error saying that the profile isn't valid.

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/603019e98b87bc000765a808/conformanceprofile/603019e98b87bc0007659f44/structure

**To Reproduce**
1. Create and lock a custom structure (example "OBX_ELR")
2. In an IG, create a user flavor named "OBX_ELR" based on the HL7 OBX object
3. Import the custom structure "OBX_ELR" as is
4. In ORU R01 message structure, set one OBX to the OBX_ELR from custom structure and another on to OBX_ELR (created from the HL7 object)
5. Export XML and validate against schema

**Expected behavior**
I'm expecting to see an error in the verification

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/108868811-904df500-75c4-11eb-97a1-ed48b07759ae.png)
![image](https://user-images.githubusercontent.com/13591511/108868918-ae1b5a00-75c4-11eb-8988-11f37bd9540b.png)
![image](https://user-images.githubusercontent.com/13591511/108868970-bc697600-75c4-11eb-8714-8485b417bdaf.png)
![image](https://user-images.githubusercontent.com/13591511/108869052-d60abd80-75c4-11eb-8320-524dcd10a088.png)
![image](https://user-images.githubusercontent.com/13591511/108869203-f8044000-75c4-11eb-9375-e448fa77634b.png)
![image](https://user-images.githubusercontent.com/13591511/108869319-12d6b480-75c5-11eb-9a01-9552775a6568.png)

**Additional context**
XML files generated:
[CUSTOM-TEST-603019e98b87bc000765a808_20210219_200630.zip](https://github.com/usnistgov/hl7-igamt/files/6030043/CUSTOM-TEST-603019e98b87bc000765a808_20210219_200630.zip)

**Comment by Jungyubw** [comment]
@carolinerosin I think that best way is to check this by XML Schema. I will try to add the feature in the XSD. Thanks

**Comment by carolinerosin** [comment]
It is already in the schemas, I thought verification was also running the schema validation, that's why I was confused.

In the end, the user should not be able to create an IG where two different segment flavor have the same name (that is a separate issue), but I think this is still something that verification should catch if possible (because this would cause the validation to fail)

**Comment by Jungyubw** [comment]
Maybe you posted after my modification of post. Currently the verification doesn't include the schema validation because there is no xml at verification time. 
We already have a logic to check duplicated flavor but I think it is not working for Custom structure. I will fix it. Thanks.

**Comment by Jungyubw** [comment]
Fixed

**Comment by Abdelghani90** [comment]
@Jungyubw I still cannot see an error about segment flavor duplication in the verification report.
@carolinerosin Please double check

**Comment by carolinerosin** [comment]
Here is it. I'm wondering if we should add that as "FATAL"
I'd like to check how GVT reacts to that profile before deciding but at the moment I can't export to XML
![image](https://user-images.githubusercontent.com/13591511/124633926-c729f680-de53-11eb-9060-f21f12908e3a.png)

**Comment by Abdelghani90** [comment]
My bad! I was looking under the segment section.

**Comment by carolinerosin** [comment]
So IGAMT generates an XML that is not processed by GVT (and validation I guess) because the XML does not comply to the schema.

I think this should be categorized as FATAL, @Jungyubw do you have an opinion (FATAL vs ERROR) ?

**Comment by Abdelghani90** [comment]
I think we need to think more about how to handle the naming and the export of the customized segment. I guess it should be handeled the same way as pre-adoption. Because even though both segments have the same name, they have different structure.
